rust-lang-nursery/lazy-static.rs

src/lazy_static.rs, tests/test.rs
Deref is no longer in the prelude, so it had to be specified using its full
path (thanks to @pczarn for the syntax). Deref's type parameter was replaced
with an associated type, Target.
Replaced [Box<uint>, ..3] with [Box<uint>; 3] because the former syntax is gone.
=> Updated for latest Rust nightly.

README.md, src/lazy_static.rs, tests/test.rs
sync::Once::doit() -> call_once()
phase/plugin is now just #[macro_use]
Added comment to tests to remind self that UNUSED should trigger dead
code warnings, because it's not clear where the dead code warnings come
from when running tests.
=> Update for rust nightly (2015-01-06)

src/lazy_static.rs, tests/test.rs
Hello,
Thanks for writing lazy_static.
* This PR fixes a build error that appeared recently in Rust nightly
* It also cleans up all outstanding warnings, so the project now builds cleanly (as of Rust b0746ff)
If you could review and release quickly, that would be ideal, since the released version doesn't build on current Rust.  The tests pass in any case.
I release all these patches under the MIT license.
=> Fix build errors and some warnings

src/lazy_static.rs, tests/test.rs
I noticed that lazy-static is running the user initialization code in an unsafe block, which seems wrong. Before I fix that, though, it seems important to be able to run the tests. The changes are minor--just some updates to slicing syntax.
Cheers,
Jesse
=> Updated tests to work with nightly 1.0.0-beta (9854143cb 2015-04-02)

src/lib.rs, tests/test.rs
Rough implementation for metadata on lazy statics. I don't think I broke anything. The syntax is as you'd expect, except for the doc comment bug we discussed on IRC. I wrote a note in the macro doc about that.
There isn't quite an obvious place to attach the metadata, since we don't really create a static of type $T, but actually a Dereffing struct and a static of type $N. The static really has no information except the name of the static, while the struct at least tells you what it Derefs into, so I went with attaching the metadata there and hiding the other one from the docs.
I had to add some commas to the internal macro syntax because of the added sequence repetitions :(
=> support metadata on statics

src/lib.rs, tests/test.rs
This is totally untested. Is Travis-CI configured on this repository?
=> Use std::intrinsics::unreachable instead of an infinite loop

src/lib.rs
Here's an example when it causes a problem: https://github.com/servo/servo/pull/10488#issue-147047204
=> Use the full path for the `Box` type.

.travis.yml, Cargo.toml, src/core_lazy.rs, src/lazy.rs, src/lib.rs, src/nightly_lazy.rs, tests/no_std.rs, tests/test.rs
=> Spinning no_std feature

src/lib.rs
Obviously, if there's something dire that needs to be changed or fixed, please let me know (or fix it). The one concern I had was the weirdness that `pub(in module)` produces with the macros, because it adds an extra argument. I've added a special rule to `__lazy_static_internal` that allows for a workaround.
=> Update to support Rust 1.18 visibility restrictions (see #80)

appveyor.yml
This is an update of `appveyor.yml` based on the https://github.com/rust-lang/libc/blob/master/appveyor.yml file.
=> Fix appveyor builds for stable channel

.travis.yml, Cargo.toml, appveyor.yml, tests/compile-fail/README.md, tests/compile-fail/static_never_used.rs, tests/compile_tests.rs, tests/test.rs
This is an initial version of compiler tests. So far it should work on travis, appveyor is a bit harder to achieve, because there's no simple way to add testing with specified features only on nightly. Please don't merge yet, because I want to at least try to make them run on appveyor as well.
Moreover due to the design of `compiletest` crate and its implementation details there isn't any clear way to annotate warnings/errors in lines that are being expanded by the macro, but rather we are forced to use `error-pattern` general mechanism. I will document that in code later on, just wanted to highlight it here.
=> Add support for compiler tests

src/lib.rs, tests/compile-fail/incorrect_visibility_restriction.rs, tests/compile-fail/static_is_private.rs, tests/test.rs
I marked the PR WIP because I'm not 100% sure one change I introduced is correct.
Closes #87
=> WIP Improved support for visibility restrictions

Cargo.toml, src/core_lazy.rs, src/lazy.rs, src/lib.rs, src/nightly_lazy.rs, tests/compile-fail/static_is_sized.rs
https://github.com/rust-lang/rfcs/pull/1440 got merged, so we can now get rid of the UnsafeCell in favor of directly having a drop type in a mutable static.
However, since the current `UnsafeCell` impl got also legitimized by the RFC, the current plan is to __not__ merge this PR until either the `drop_types_in_const` feature gets stabilized, or is at least old enough to not require the most current version of the compiler.
=> Switch lazy_static over to mutable statics instead of UnsafeCell on nightly

.travis.yml, Cargo.toml, appveyor.yml, compiletest/Cargo.toml, compiletest/src/lib.rs, compiletest/tests/compile-fail/README.md, compiletest/tests/compile-fail/incorrect_visibility_restriction.rs, compiletest/tests/compile-fail/static_is_private.rs, compiletest/tests/compile-fail/static_is_sized.rs, compiletest/tests/compile-fail/static_never_used.rs, compiletest/tests/compile_tests.rs, src/nightly_lazy.rs
Based on #97 
I also had a look at our compile fail tests, looks like our `rustc` invocations can't disambiguate between the `lazy_static` that ships with the Rust toolchain and the `lazy_static` we build locally. I've 'fixed' this up by wrapping `lazy_static` in a shim with a different name. It seems to work.
cc @Kimundi @superp00t
=> Fix nightly build

compiletest/tests/compile-fail/static_is_sized.rs
Looks like the error messages for unsized types have been improved.
=> Update unsized error msg pattern

src/lib.rs
This fixes the following error when using Rust 2018 style macro imports.
```rust
extern crate lazy_static;
use lazy_static::lazy_static;
```
```
error: cannot find macro `__lazy_static_internal!` in this scope
--> src/main.rs:8:1
|
8  | / lazy_static! {
9  | |     static ref M: HashMap<String, String> = HashMap::new();
10 | | }
| |_^
|
```
The `local_inner_macros` modifier resolves all macro invocations made from within that macro as helpers in the same crate. So if `lazy_static!` expands to an invocation of `__lazy_static_internal!` then this would be resolved as `$crate::__lazy_static_internal!` rather than requiring the caller to have `__lazy_static_internal` in scope.
The attribute is ignored by pre-2018 compilers so lazy_static will continue to work as normal with `#[macro_use]`.
In …
=> Use local_inner_macros to resolve all helper macros within $crate

Cargo.toml, build.rs
We shouldn't need to pull in a dependency on a production-quality semver implementation to tell whether \>=1.22.0 is met. The version_check crate is intended for exactly this build script use case and compiles more than twice as fast.
=> Switch to version_check

Cargo.toml, README.md, src/lib.rs
Including #103 which fixes a soundness issue with public fields and introduces a build script to automatically select an appropriate implementation based on the available compiler.
I went for the conservative versioning approach of `1.1.0` instead of `1.0.3` since the implementation of `lazy_static` may change, but if anyone would prefer a patch I'll update it.
=> Prepare for 1.1.0 release

.travis.yml, src/heap_lazy.rs, src/inline_lazy.rs, src/lib.rs
Fixes #117 
cc @eddyb @RalfJung
See #117 for more details, we don't need `&'static mut self` receivers on `Lazy` to initialise and get its value. This also has the nice side benefit of making our various `Lazy` impls have a consistent API.
This is a potentially breaking change, @pietroalbini do you think it would be possible to schedule a crater run? Thanks!
=> Fix a soundness hole allowing multiple mutable borrows

.travis.yml, Cargo.toml, src/core_lazy.rs, src/lib.rs, tests/no_std.rs
I am opening a different pull request since this is different from #122 
We should now be able to have no_std lazy_static with stable Rust.
=> using the stable spin's once implementation

Cargo.toml, README.md
[Current changeset](https://github.com/rust-lang-nursery/lazy-static.rs/compare/1.1.0...master)
This release includes a change that bumps our minimum supported rustc version from `1.21.0` to `1.24.1` in order to solve a soundness issue (see #117 for details). This compiler version does seem to be readily available in package managers.
cc @Kimundi @eddyb @RalfJung
also cc @BurntSushi @jethrogb (who might be interested in the minimum version bump)
=> Prepare for 1.2.0 release

Cargo.toml
This PR fixes #136, since the nightly feature is now redundant.
=> Remove redundant nightly feature, fixes #136

src/lib.rs
Following up for #136 
Just removes a reference to the `nightly` feature (that was removed in #138) from the crate docs.
I thought I'd leave the CI jobs for building and checking on `nightly` just because it's nice to know whether the `nightly` channel manages to break in some way so that can get reported back upstream.
cc @Ericson2314
=> Remove reference to the nightly feature from crate docs

Cargo.toml
Updates `spin` dependency to `0.5.0`, also omitting the `once` feature flag from it, as it was removed.
=> Update spin to 0.5.0

Cargo.toml, README.md, src/lib.rs
[Changes since the last release](https://github.com/rust-lang-nursery/lazy-static.rs/compare/1.2.0...master)
Includes:
- #139 
- #140 
- #142 
I figured we should bump the minor version since we are removing the now unused unstable `nightly` feature flag.
=> Prepare for 1.3.0 release

.travis.yml, README.md, src/inline_lazy.rs
closes #154
I think it's worth bumping MSRV to get rid of `uninitialized::<Void>`.
=> bump MSRV to 1.27.2

Cargo.toml, README.md, src/lib.rs
[Changes since the last release](https://github.com/rust-lang-nursery/lazy-static.rs/compare/1.3.0...master)
Includes:
- #144
- #145
- #152
- #155
This release will bump our minimum Rust version to `1.27`.
=> Prepare for 1.4.0 release

.travis.yml, README.md, src/lib.rs
Don't run 1.27.2 doc examples (based off #134)
=> Update examples for 2018 edition

tests/test.rs
@Kimundi small fix removed unused braces
```
warning: unnecessary braces around block return value
--> tests/test.rs:108:31
|
108 |     pub static ref VAR: i32 = { 0 };
|                               ^^^^^ help: remove these braces
|
= note: `#[warn(unused_braces)]` on by default
```
=> test: VAR; remove unused braces

Cargo.toml
`spin` 0.7 includes performance improvements such as less strict ordering requirements and better spinning. All in all, this should reduce power consumption and improve performance, particularly on platforms like ARM.
=> Upgraded spin to 0.7 for better performance

.travis.yml, README.md, src/inline_lazy.rs
This avoids unneeded tag in `Option` and addresses FIXME comment.
=> Replace `Option<T>` with `MaybeUninit<T>`

Cargo.toml, README.md, src/lib.rs
[Changes since the last release](https://github.com/rust-lang-nursery/lazy-static.rs/compare/1.4.0...master)
Includes:
- #159
- #172
- #175
- #177
- #173
- #179
- #182
=> Prepare for 1.5.0 release

src/lib.rs, tests/test.rs
Closes #153
This is a bit of a bandaid fix that just unconditionally applies `#[allow(non_upper_case_globals)]` on the generated global in the same way we do for non-camel-case type names. With some refactoring to expand to a `const _: () {}` block we could probably make the way attributes are applied to the expanded code consistent but since we're in life-support mode I've just opted for the simplest approach.
=> Apply non-upper-case-globals to generated statics

.travis.yml, README.md
As said in https://github.com/rust-lang-nursery/lazy-static.rs/pull/186#issuecomment-838856179, the actual MSRV of lazy_static 1.5.0 is 1.40.
=> Fix MSRV in readme and CI

Cargo.toml
Already released and fixed a bug for `Once`.
Should be great before lazy-static get officially updated to **1.5.0**.
=> Update spin to 0.9.3
